### ISSUE TITLE
(Perl update?) Can't call method catch on undefined value

### ISSUE THREAD

**Issue by utrack** [doy/try-tiny#23]
Hey,
I'm using Perl v 5.20.1 (It was updated recently) and I started to receive an odd bug:

Code (simplified):

try {
   someprocedure(); # does not throw anything, if error then everything is okay
} catch {
 print "Error: $_";
};

If anything is thrown then it works and outputs an error, but when nothing is thrown it complains about
(1) undefined $_ when concatenating string for print
(2) if I'm adding check like if ($_) it throws "Can't call method "catch" on an undefined value".

**Comment by doy** [comment]
This sounds like you're missing a `use Try::Tiny` somewhere. Can you give me a sample script that demonstrates this error?

**Comment by utrack** [comment]
Yeah, sorry! Found out someone else was moving code in the same time. Guess that one can be closed :)
